### ISSUE TITLE
Collect profile info failed, return empty array Check spider progress

### ISSUE THREAD

**Issue by qianxuwanyu** [FaustRen/facebook-graphql-scraper#1]
Collect profile info failed, return empty array
Check spider progress. 可以帮忙看一下吗，直接启动报这个错，拜托啦，没办法直接联系您

**Comment by FaustRen** [comment]
Hi @qianxuwanyu,

我已暫時性地修復了這個問題。你可以使用 pip install facebook-graphql-scraper -U 更新到最新版本。
在未登入帳號時，爬蟲程式搜集profile資訊容易出現問題。不過，程式不會因此中斷，仍能順利撈取貼文資訊。
未來，我會努力尋找更穩定的方法來撈取profile資料。


I have temporarily fixed the issue. You can update to the latest version using pip install facebook-graphql-scraper -U.
The crawler program encounters issues more easily when collecting profile information without logging into the account. However, it doesn't interrupt the program and continues to fetch post information successfully.
In the future, I will strive to find a more stable method for data retrieval.

**Comment by FaustRen** [comment]
Hi @qianxuwanyu ,

As there has been no response, I am closing this issue. If you continue to experience the problem, please feel free to reopen the issue or create a new one.

Best,
Ren
